### ISSUE TITLE
Create new entries for the pipeline

### ISSUE THREAD

**Issue by jvfe** [beiko-lab/arete#143]
- [x] Phylogenomics
- [x] rSPR
- [x] evolCCM
- [x] Recombination 
- [ ] Gene Order

**Comment by rbeiko** [comment]
Would it make sense to have entries for all subworkflows? I'm thinking additionally of pan-genomics at the moment but we will eventually want to consider dynamics and gene order.

Similarly we might allow the user to exit the pipeline at a given point in the pipeline.

**Comment by jvfe** [comment]
> Would it make sense to have entries for all subworkflows? I'm thinking additionally of pan-genomics at the moment but we will eventually want to consider dynamics and gene order.
> 
> Similarly we might allow the user to exit the pipeline at a given point in the pipeline.

So, currently phylogenomics/pangenomics is in the same subworkflow, since that's how it was first implemented. They'll both be present in the phylogenomics entry, or should that be refacotred?

**Comment by rbeiko** [comment]
Let's leave it like that for now. Separating them can be for V2 or V6.
